# Generated by Django 5.1.2 on 2024-10-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='possible_outcomes',
        ),
    ]
