# Generated by Django 5.1.2 on 2024-10-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_remove_target_possible_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='targets.target'),
            preserve_default=False,
        ),
    ]
